version: '3.7'
services:
  neo4j:
    image: neo4j:4.1.4-enterprise
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
      - NEO4JLABS_PLUGINS=["apoc","graph-data-science"]